# Generated by Django 5.1.1 on 2024-10-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0002_techstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('CWID', models.CharField(max_length=9, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TechStudent',
        ),
    ]
