# Generated by Django 5.1.1 on 2024-10-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0004_riderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='status',
        ),
    ]
