# Generated by Django 5.1.1 on 2024-10-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0005_remove_riderequest_rider_remove_riderequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=12)),
            ],
        ),
    ]
