# Generated by Django 5.1.1 on 2024-10-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0006_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
