# Generated by Django 5.1.1 on 2024-10-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0007_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='CWID',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='prefered_drivers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Univah.driver'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Univah.rider'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
