# Generated by Django 5.1.1 on 2024-10-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0008_driver_cwid_driver_email_rider_prefered_drivers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='dropoff_location',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='riderequest',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
    ]
