# Generated by Django 5.1.1 on 2024-10-28 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0010_driver_password_rider_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='first_name',
            new_name='preferred_drivers',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='CWID',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='CWID',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='password',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='prefered_drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='Univah.driver'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='Univah.rider'),
        ),
    ]
