# Generated by Django 5.1.1 on 2024-10-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0011_rename_first_name_rider_preferred_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='preferred_drivers',
        ),
    ]
