# Generated by Django 5.1.1 on 2024-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0012_remove_rider_preferred_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='booking_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
