# Generated by Django 5.1.1 on 2024-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0013_riderequest_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
