# Generated by Django 5.1.1 on 2024-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univah', '0014_driver_major_rider_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
